/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface IGameLogicInterface extends Interface {
    getFunction(nameOrSignature: "grantXP" | "mintItem"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'grantXP', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'mintItem', values: [AddressLike, string, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'grantXP', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mintItem', data: BytesLike): Result;
  }

  

  export interface IGameLogic extends BaseContract {
    
    connect(runner?: ContractRunner | null): IGameLogic;
    waitForDeployment(): Promise<this>;

    interface: IGameLogicInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    grantXP: TypedContractMethod<
      [player: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    mintItem: TypedContractMethod<
      [to: AddressLike, uri: string, initialXP: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'grantXP'): TypedContractMethod<
      [player: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'mintItem'): TypedContractMethod<
      [to: AddressLike, uri: string, initialXP: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }