/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IGameItem } from './IGameItem.js';
export type { IGameLogic } from './IGameLogic.js';
export type { QuestManager } from './QuestManager.js';