/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface QuestManagerInterface extends Interface {
    getFunction(nameOrSignature: "addQuest" | "completeQuest" | "completed" | "gameItem" | "gameLogic" | "getQuest" | "owner" | "purgeCompleted" | "questVerifier" | "quests" | "renounceOwnership" | "setQuestVerifier" | "transferOwnership" | "tryRecoverSignature"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "OwnershipTransferred" | "QuestAdded" | "QuestCompleted"): EventFragment;

    encodeFunctionData(functionFragment: 'addQuest', values: [BigNumberish, BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'completeQuest', values: [BigNumberish, BytesLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'completed', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'gameItem', values?: undefined): string;
encodeFunctionData(functionFragment: 'gameLogic', values?: undefined): string;
encodeFunctionData(functionFragment: 'getQuest', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'purgeCompleted', values: [AddressLike, BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'questVerifier', values?: undefined): string;
encodeFunctionData(functionFragment: 'quests', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'setQuestVerifier', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'tryRecoverSignature', values: [BytesLike, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'addQuest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'completeQuest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'completed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'gameItem', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'gameLogic', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getQuest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'purgeCompleted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'questVerifier', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'quests', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setQuestVerifier', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tryRecoverSignature', data: BytesLike): Result;
  }

  
    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace QuestAddedEvent {
      export type InputTuple = [id: BigNumberish, xpReward: BigNumberish, nftUri: string];
      export type OutputTuple = [id: bigint, xpReward: bigint, nftUri: string];
      export interface OutputObject {id: bigint, xpReward: bigint, nftUri: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace QuestCompletedEvent {
      export type InputTuple = [player: AddressLike, questId: BigNumberish, xp: BigNumberish];
      export type OutputTuple = [player: string, questId: bigint, xp: bigint];
      export interface OutputObject {player: string, questId: bigint, xp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface QuestManager extends BaseContract {
    
    connect(runner?: ContractRunner | null): QuestManager;
    waitForDeployment(): Promise<this>;

    interface: QuestManagerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addQuest: TypedContractMethod<
      [id: BigNumberish, xpReward: BigNumberish, nftUri: string, ],
      [void],
      'nonpayable'
    >
    

    
    completeQuest: TypedContractMethod<
      [questId: BigNumberish, signature: BytesLike, player: AddressLike, deadline: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    completed: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    gameItem: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    gameLogic: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getQuest: TypedContractMethod<
      [id: BigNumberish, ],
      [[bigint, string, boolean] & {xpReward: bigint, nftUri: string, exists: boolean }],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    purgeCompleted: TypedContractMethod<
      [player: AddressLike, questIds: BigNumberish[], ],
      [void],
      'nonpayable'
    >
    

    
    questVerifier: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    quests: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, boolean] & {xpReward: bigint, nftUri: string, exists: boolean }],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setQuestVerifier: TypedContractMethod<
      [_verifier: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    tryRecoverSignature: TypedContractMethod<
      [digest: BytesLike, signature: BytesLike, ],
      [[boolean, string]],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addQuest'): TypedContractMethod<
      [id: BigNumberish, xpReward: BigNumberish, nftUri: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'completeQuest'): TypedContractMethod<
      [questId: BigNumberish, signature: BytesLike, player: AddressLike, deadline: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'completed'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'gameItem'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'gameLogic'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getQuest'): TypedContractMethod<
      [id: BigNumberish, ],
      [[bigint, string, boolean] & {xpReward: bigint, nftUri: string, exists: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'purgeCompleted'): TypedContractMethod<
      [player: AddressLike, questIds: BigNumberish[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'questVerifier'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'quests'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, boolean] & {xpReward: bigint, nftUri: string, exists: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setQuestVerifier'): TypedContractMethod<
      [_verifier: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'tryRecoverSignature'): TypedContractMethod<
      [digest: BytesLike, signature: BytesLike, ],
      [[boolean, string]],
      'view'
    >;

    getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'QuestAdded'): TypedContractEvent<QuestAddedEvent.InputTuple, QuestAddedEvent.OutputTuple, QuestAddedEvent.OutputObject>;
getEvent(key: 'QuestCompleted'): TypedContractEvent<QuestCompletedEvent.InputTuple, QuestCompletedEvent.OutputTuple, QuestCompletedEvent.OutputObject>;

    filters: {
      
      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'QuestAdded(uint256,uint256,string)': TypedContractEvent<QuestAddedEvent.InputTuple, QuestAddedEvent.OutputTuple, QuestAddedEvent.OutputObject>;
      QuestAdded: TypedContractEvent<QuestAddedEvent.InputTuple, QuestAddedEvent.OutputTuple, QuestAddedEvent.OutputObject>;
    

      'QuestCompleted(address,uint256,uint256)': TypedContractEvent<QuestCompletedEvent.InputTuple, QuestCompletedEvent.OutputTuple, QuestCompletedEvent.OutputObject>;
      QuestCompleted: TypedContractEvent<QuestCompletedEvent.InputTuple, QuestCompletedEvent.OutputTuple, QuestCompletedEvent.OutputObject>;
    
    };
  }