/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface EduPlatformInterface extends Interface {
    getFunction(nameOrSignature: "BPS_DENOMINATOR" | "DAILY_REWARD_CAP" | "KYC_MINIMUM" | "REVENUE_BURN_BPS" | "completeCourse" | "courseCompleted" | "courseCount" | "courses" | "createCourse" | "credentialTokenId" | "deactivateCourse" | "eduToken" | "getLearnerStats" | "mintCredential" | "owner" | "profiles" | "receivePayment" | "registerLearner" | "renounceOwnership" | "rewardRecipients" | "setKYCTier" | "totalBurned" | "transferOwnership"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CourseCompleted" | "CourseCreated" | "CourseDeactivated" | "CredentialMinted" | "KYCUpdated" | "OwnershipTransferred" | "ProfileCreated" | "RevenueReceived" | "TokensBurned"): EventFragment;

    encodeFunctionData(functionFragment: 'BPS_DENOMINATOR', values?: undefined): string;
encodeFunctionData(functionFragment: 'DAILY_REWARD_CAP', values?: undefined): string;
encodeFunctionData(functionFragment: 'KYC_MINIMUM', values?: undefined): string;
encodeFunctionData(functionFragment: 'REVENUE_BURN_BPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'completeCourse', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'courseCompleted', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'courseCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'courses', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createCourse', values: [BigNumberish, BigNumberish, BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'credentialTokenId', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'deactivateCourse', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'eduToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'getLearnerStats', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'mintCredential', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'profiles', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'receivePayment', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'registerLearner', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'rewardRecipients', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setKYCTier', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'totalBurned', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'BPS_DENOMINATOR', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DAILY_REWARD_CAP', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'KYC_MINIMUM', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'REVENUE_BURN_BPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'completeCourse', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'courseCompleted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'courseCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'courses', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createCourse', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'credentialTokenId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deactivateCourse', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'eduToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getLearnerStats', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mintCredential', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'profiles', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'receivePayment', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerLearner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rewardRecipients', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setKYCTier', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalBurned', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  }

  
    export namespace CourseCompletedEvent {
      export type InputTuple = [learner: AddressLike, courseId: BigNumberish];
      export type OutputTuple = [learner: string, courseId: bigint];
      export interface OutputObject {learner: string, courseId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CourseCreatedEvent {
      export type InputTuple = [id: BigNumberish, eduReward: BigNumberish, metadataUri: string];
      export type OutputTuple = [id: bigint, eduReward: bigint, metadataUri: string];
      export interface OutputObject {id: bigint, eduReward: bigint, metadataUri: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CourseDeactivatedEvent {
      export type InputTuple = [courseId: BigNumberish];
      export type OutputTuple = [courseId: bigint];
      export interface OutputObject {courseId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CredentialMintedEvent {
      export type InputTuple = [learner: AddressLike, courseId: BigNumberish, tokenId: BigNumberish];
      export type OutputTuple = [learner: string, courseId: bigint, tokenId: bigint];
      export interface OutputObject {learner: string, courseId: bigint, tokenId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace KYCUpdatedEvent {
      export type InputTuple = [learner: AddressLike, tier: BigNumberish];
      export type OutputTuple = [learner: string, tier: bigint];
      export interface OutputObject {learner: string, tier: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProfileCreatedEvent {
      export type InputTuple = [learner: AddressLike];
      export type OutputTuple = [learner: string];
      export interface OutputObject {learner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RevenueReceivedEvent {
      export type InputTuple = [payer: AddressLike, amount: BigNumberish];
      export type OutputTuple = [payer: string, amount: bigint];
      export interface OutputObject {payer: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokensBurnedEvent {
      export type InputTuple = [amount: BigNumberish, totalBurned: BigNumberish];
      export type OutputTuple = [amount: bigint, totalBurned: bigint];
      export interface OutputObject {amount: bigint, totalBurned: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface EduPlatform extends BaseContract {
    
    connect(runner?: ContractRunner | null): EduPlatform;
    waitForDeployment(): Promise<this>;

    interface: EduPlatformInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    BPS_DENOMINATOR: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    DAILY_REWARD_CAP: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    KYC_MINIMUM: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    REVENUE_BURN_BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    completeCourse: TypedContractMethod<
      [courseId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    courseCompleted: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    courseCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    courses: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint, bigint, boolean, string] & {id: bigint, eduReward: bigint, credentialPrice: bigint, active: boolean, metadataUri: string }],
      'view'
    >
    

    
    createCourse: TypedContractMethod<
      [id: BigNumberish, eduReward: BigNumberish, credentialPrice: BigNumberish, metadataUri: string, ],
      [void],
      'nonpayable'
    >
    

    
    credentialTokenId: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    deactivateCourse: TypedContractMethod<
      [courseId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    eduToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getLearnerStats: TypedContractMethod<
      [learner: AddressLike, ],
      [[bigint, bigint, bigint, bigint] & {kycTier: bigint, totalXp: bigint, coursesCompleted: bigint, dailyRemaining: bigint }],
      'view'
    >
    

    
    mintCredential: TypedContractMethod<
      [courseId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    profiles: TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, bigint, bigint, bigint, bigint, boolean] & {kycTier: bigint, totalXp: bigint, coursesCompleted: bigint, dailyRewardsClaimed: bigint, lastRewardDay: bigint, exists: boolean }],
      'view'
    >
    

    
    receivePayment: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    registerLearner: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    rewardRecipients: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    setKYCTier: TypedContractMethod<
      [learner: AddressLike, tier: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    totalBurned: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'BPS_DENOMINATOR'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'DAILY_REWARD_CAP'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'KYC_MINIMUM'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'REVENUE_BURN_BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'completeCourse'): TypedContractMethod<
      [courseId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'courseCompleted'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'courseCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'courses'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint, bigint, boolean, string] & {id: bigint, eduReward: bigint, credentialPrice: bigint, active: boolean, metadataUri: string }],
      'view'
    >;
getFunction(nameOrSignature: 'createCourse'): TypedContractMethod<
      [id: BigNumberish, eduReward: BigNumberish, credentialPrice: BigNumberish, metadataUri: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'credentialTokenId'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'deactivateCourse'): TypedContractMethod<
      [courseId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'eduToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getLearnerStats'): TypedContractMethod<
      [learner: AddressLike, ],
      [[bigint, bigint, bigint, bigint] & {kycTier: bigint, totalXp: bigint, coursesCompleted: bigint, dailyRemaining: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'mintCredential'): TypedContractMethod<
      [courseId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'profiles'): TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, bigint, bigint, bigint, bigint, boolean] & {kycTier: bigint, totalXp: bigint, coursesCompleted: bigint, dailyRewardsClaimed: bigint, lastRewardDay: bigint, exists: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'receivePayment'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'registerLearner'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'rewardRecipients'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'setKYCTier'): TypedContractMethod<
      [learner: AddressLike, tier: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalBurned'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'CourseCompleted'): TypedContractEvent<CourseCompletedEvent.InputTuple, CourseCompletedEvent.OutputTuple, CourseCompletedEvent.OutputObject>;
getEvent(key: 'CourseCreated'): TypedContractEvent<CourseCreatedEvent.InputTuple, CourseCreatedEvent.OutputTuple, CourseCreatedEvent.OutputObject>;
getEvent(key: 'CourseDeactivated'): TypedContractEvent<CourseDeactivatedEvent.InputTuple, CourseDeactivatedEvent.OutputTuple, CourseDeactivatedEvent.OutputObject>;
getEvent(key: 'CredentialMinted'): TypedContractEvent<CredentialMintedEvent.InputTuple, CredentialMintedEvent.OutputTuple, CredentialMintedEvent.OutputObject>;
getEvent(key: 'KYCUpdated'): TypedContractEvent<KYCUpdatedEvent.InputTuple, KYCUpdatedEvent.OutputTuple, KYCUpdatedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'ProfileCreated'): TypedContractEvent<ProfileCreatedEvent.InputTuple, ProfileCreatedEvent.OutputTuple, ProfileCreatedEvent.OutputObject>;
getEvent(key: 'RevenueReceived'): TypedContractEvent<RevenueReceivedEvent.InputTuple, RevenueReceivedEvent.OutputTuple, RevenueReceivedEvent.OutputObject>;
getEvent(key: 'TokensBurned'): TypedContractEvent<TokensBurnedEvent.InputTuple, TokensBurnedEvent.OutputTuple, TokensBurnedEvent.OutputObject>;

    filters: {
      
      'CourseCompleted(address,uint256)': TypedContractEvent<CourseCompletedEvent.InputTuple, CourseCompletedEvent.OutputTuple, CourseCompletedEvent.OutputObject>;
      CourseCompleted: TypedContractEvent<CourseCompletedEvent.InputTuple, CourseCompletedEvent.OutputTuple, CourseCompletedEvent.OutputObject>;
    

      'CourseCreated(uint256,uint256,string)': TypedContractEvent<CourseCreatedEvent.InputTuple, CourseCreatedEvent.OutputTuple, CourseCreatedEvent.OutputObject>;
      CourseCreated: TypedContractEvent<CourseCreatedEvent.InputTuple, CourseCreatedEvent.OutputTuple, CourseCreatedEvent.OutputObject>;
    

      'CourseDeactivated(uint256)': TypedContractEvent<CourseDeactivatedEvent.InputTuple, CourseDeactivatedEvent.OutputTuple, CourseDeactivatedEvent.OutputObject>;
      CourseDeactivated: TypedContractEvent<CourseDeactivatedEvent.InputTuple, CourseDeactivatedEvent.OutputTuple, CourseDeactivatedEvent.OutputObject>;
    

      'CredentialMinted(address,uint256,uint256)': TypedContractEvent<CredentialMintedEvent.InputTuple, CredentialMintedEvent.OutputTuple, CredentialMintedEvent.OutputObject>;
      CredentialMinted: TypedContractEvent<CredentialMintedEvent.InputTuple, CredentialMintedEvent.OutputTuple, CredentialMintedEvent.OutputObject>;
    

      'KYCUpdated(address,uint256)': TypedContractEvent<KYCUpdatedEvent.InputTuple, KYCUpdatedEvent.OutputTuple, KYCUpdatedEvent.OutputObject>;
      KYCUpdated: TypedContractEvent<KYCUpdatedEvent.InputTuple, KYCUpdatedEvent.OutputTuple, KYCUpdatedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'ProfileCreated(address)': TypedContractEvent<ProfileCreatedEvent.InputTuple, ProfileCreatedEvent.OutputTuple, ProfileCreatedEvent.OutputObject>;
      ProfileCreated: TypedContractEvent<ProfileCreatedEvent.InputTuple, ProfileCreatedEvent.OutputTuple, ProfileCreatedEvent.OutputObject>;
    

      'RevenueReceived(address,uint256)': TypedContractEvent<RevenueReceivedEvent.InputTuple, RevenueReceivedEvent.OutputTuple, RevenueReceivedEvent.OutputObject>;
      RevenueReceived: TypedContractEvent<RevenueReceivedEvent.InputTuple, RevenueReceivedEvent.OutputTuple, RevenueReceivedEvent.OutputObject>;
    

      'TokensBurned(uint256,uint256)': TypedContractEvent<TokensBurnedEvent.InputTuple, TokensBurnedEvent.OutputTuple, TokensBurnedEvent.OutputObject>;
      TokensBurned: TypedContractEvent<TokensBurnedEvent.InputTuple, TokensBurnedEvent.OutputTuple, TokensBurnedEvent.OutputObject>;
    
    };
  }