/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface GameLogicInterface extends Interface {
    getFunction(nameOrSignature: "gameItem" | "grantXP" | "itemLevel" | "mintItem" | "owner" | "renounceOwnership" | "spendXP" | "transferOwnership" | "upgradeItem" | "xpBalance"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ItemMinted" | "ItemUpgraded" | "OwnershipTransferred" | "XPGained" | "XPSpent"): EventFragment;

    encodeFunctionData(functionFragment: 'gameItem', values?: undefined): string;
encodeFunctionData(functionFragment: 'grantXP', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'itemLevel', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'mintItem', values: [AddressLike, string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'spendXP', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'upgradeItem', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'xpBalance', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'gameItem', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantXP', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'itemLevel', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mintItem', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'spendXP', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'upgradeItem', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'xpBalance', data: BytesLike): Result;
  }

  
    export namespace ItemMintedEvent {
      export type InputTuple = [player: AddressLike, tokenId: BigNumberish, uri: string];
      export type OutputTuple = [player: string, tokenId: bigint, uri: string];
      export interface OutputObject {player: string, tokenId: bigint, uri: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ItemUpgradedEvent {
      export type InputTuple = [player: AddressLike, tokenId: BigNumberish, newLevel: BigNumberish];
      export type OutputTuple = [player: string, tokenId: bigint, newLevel: bigint];
      export interface OutputObject {player: string, tokenId: bigint, newLevel: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace XPGainedEvent {
      export type InputTuple = [player: AddressLike, amount: BigNumberish, total: BigNumberish];
      export type OutputTuple = [player: string, amount: bigint, total: bigint];
      export interface OutputObject {player: string, amount: bigint, total: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace XPSpentEvent {
      export type InputTuple = [player: AddressLike, amount: BigNumberish, remaining: BigNumberish];
      export type OutputTuple = [player: string, amount: bigint, remaining: bigint];
      export interface OutputObject {player: string, amount: bigint, remaining: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface GameLogic extends BaseContract {
    
    connect(runner?: ContractRunner | null): GameLogic;
    waitForDeployment(): Promise<this>;

    interface: GameLogicInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    gameItem: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    grantXP: TypedContractMethod<
      [player: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    itemLevel: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    mintItem: TypedContractMethod<
      [to: AddressLike, uri: string, initialXP: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    spendXP: TypedContractMethod<
      [player: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    upgradeItem: TypedContractMethod<
      [tokenId: BigNumberish, xpCost: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    xpBalance: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'gameItem'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'grantXP'): TypedContractMethod<
      [player: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'itemLevel'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'mintItem'): TypedContractMethod<
      [to: AddressLike, uri: string, initialXP: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'spendXP'): TypedContractMethod<
      [player: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'upgradeItem'): TypedContractMethod<
      [tokenId: BigNumberish, xpCost: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'xpBalance'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;

    getEvent(key: 'ItemMinted'): TypedContractEvent<ItemMintedEvent.InputTuple, ItemMintedEvent.OutputTuple, ItemMintedEvent.OutputObject>;
getEvent(key: 'ItemUpgraded'): TypedContractEvent<ItemUpgradedEvent.InputTuple, ItemUpgradedEvent.OutputTuple, ItemUpgradedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'XPGained'): TypedContractEvent<XPGainedEvent.InputTuple, XPGainedEvent.OutputTuple, XPGainedEvent.OutputObject>;
getEvent(key: 'XPSpent'): TypedContractEvent<XPSpentEvent.InputTuple, XPSpentEvent.OutputTuple, XPSpentEvent.OutputObject>;

    filters: {
      
      'ItemMinted(address,uint256,string)': TypedContractEvent<ItemMintedEvent.InputTuple, ItemMintedEvent.OutputTuple, ItemMintedEvent.OutputObject>;
      ItemMinted: TypedContractEvent<ItemMintedEvent.InputTuple, ItemMintedEvent.OutputTuple, ItemMintedEvent.OutputObject>;
    

      'ItemUpgraded(address,uint256,uint8)': TypedContractEvent<ItemUpgradedEvent.InputTuple, ItemUpgradedEvent.OutputTuple, ItemUpgradedEvent.OutputObject>;
      ItemUpgraded: TypedContractEvent<ItemUpgradedEvent.InputTuple, ItemUpgradedEvent.OutputTuple, ItemUpgradedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'XPGained(address,uint256,uint256)': TypedContractEvent<XPGainedEvent.InputTuple, XPGainedEvent.OutputTuple, XPGainedEvent.OutputObject>;
      XPGained: TypedContractEvent<XPGainedEvent.InputTuple, XPGainedEvent.OutputTuple, XPGainedEvent.OutputObject>;
    

      'XPSpent(address,uint256,uint256)': TypedContractEvent<XPSpentEvent.InputTuple, XPSpentEvent.OutputTuple, XPSpentEvent.OutputObject>;
      XPSpent: TypedContractEvent<XPSpentEvent.InputTuple, XPSpentEvent.OutputTuple, XPSpentEvent.OutputObject>;
    
    };
  }