/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface GovernanceInterface extends Interface {
    getFunction(nameOrSignature: "cancelProposal" | "createProposal" | "createProposalWithTarget" | "eduToken" | "executeProposal" | "getProposalState" | "hasVoted" | "owner" | "proposalCount" | "proposalThreshold" | "proposals" | "quorumThreshold" | "renounceOwnership" | "setProposalThreshold" | "setQuorumThreshold" | "setVotingPeriod" | "transferOwnership" | "vote" | "voteChoice" | "voteSnapshot" | "votingPeriod"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "OwnershipTransferred" | "ProposalCanceled" | "ProposalCreated" | "ProposalExecuted" | "ProposalThresholdUpdated" | "QuorumUpdated" | "Voted" | "VotingPeriodUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'cancelProposal', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createProposal', values: [string]): string;
encodeFunctionData(functionFragment: 'createProposalWithTarget', values: [string, AddressLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'eduToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'executeProposal', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getProposalState', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'hasVoted', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'proposalCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'proposalThreshold', values?: undefined): string;
encodeFunctionData(functionFragment: 'proposals', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'quorumThreshold', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'setProposalThreshold', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setQuorumThreshold', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setVotingPeriod', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'vote', values: [BigNumberish, boolean]): string;
encodeFunctionData(functionFragment: 'voteChoice', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'voteSnapshot', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'votingPeriod', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'cancelProposal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createProposal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createProposalWithTarget', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'eduToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'executeProposal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getProposalState', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasVoted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proposalCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proposalThreshold', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proposals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'quorumThreshold', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setProposalThreshold', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setQuorumThreshold', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setVotingPeriod', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vote', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'voteChoice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'voteSnapshot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'votingPeriod', data: BytesLike): Result;
  }

  
    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProposalCanceledEvent {
      export type InputTuple = [id: BigNumberish];
      export type OutputTuple = [id: bigint];
      export interface OutputObject {id: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProposalCreatedEvent {
      export type InputTuple = [id: BigNumberish, proposer: AddressLike, description: string, startBlock: BigNumberish, endBlock: BigNumberish];
      export type OutputTuple = [id: bigint, proposer: string, description: string, startBlock: bigint, endBlock: bigint];
      export interface OutputObject {id: bigint, proposer: string, description: string, startBlock: bigint, endBlock: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProposalExecutedEvent {
      export type InputTuple = [id: BigNumberish];
      export type OutputTuple = [id: bigint];
      export interface OutputObject {id: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProposalThresholdUpdatedEvent {
      export type InputTuple = [newThreshold: BigNumberish];
      export type OutputTuple = [newThreshold: bigint];
      export interface OutputObject {newThreshold: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace QuorumUpdatedEvent {
      export type InputTuple = [newQuorum: BigNumberish];
      export type OutputTuple = [newQuorum: bigint];
      export interface OutputObject {newQuorum: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VotedEvent {
      export type InputTuple = [id: BigNumberish, voter: AddressLike, support: boolean, weight: BigNumberish];
      export type OutputTuple = [id: bigint, voter: string, support: boolean, weight: bigint];
      export interface OutputObject {id: bigint, voter: string, support: boolean, weight: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VotingPeriodUpdatedEvent {
      export type InputTuple = [newPeriod: BigNumberish];
      export type OutputTuple = [newPeriod: bigint];
      export interface OutputObject {newPeriod: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Governance extends BaseContract {
    
    connect(runner?: ContractRunner | null): Governance;
    waitForDeployment(): Promise<this>;

    interface: GovernanceInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    cancelProposal: TypedContractMethod<
      [proposalId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    createProposal: TypedContractMethod<
      [description: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    createProposalWithTarget: TypedContractMethod<
      [description: string, target: AddressLike, callData: BytesLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    eduToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    executeProposal: TypedContractMethod<
      [proposalId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getProposalState: TypedContractMethod<
      [proposalId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    hasVoted: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    proposalCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    proposalThreshold: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    proposals: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, bigint, bigint, bigint, bigint, boolean, boolean, string, string] & {id: bigint, proposer: string, description: string, forVotes: bigint, againstVotes: bigint, startBlock: bigint, endBlock: bigint, executed: boolean, canceled: boolean, target: string, callData: string }],
      'view'
    >
    

    
    quorumThreshold: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setProposalThreshold: TypedContractMethod<
      [_threshold: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setQuorumThreshold: TypedContractMethod<
      [_quorum: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setVotingPeriod: TypedContractMethod<
      [_period: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    vote: TypedContractMethod<
      [proposalId: BigNumberish, support: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    voteChoice: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    voteSnapshot: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    votingPeriod: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'cancelProposal'): TypedContractMethod<
      [proposalId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createProposal'): TypedContractMethod<
      [description: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createProposalWithTarget'): TypedContractMethod<
      [description: string, target: AddressLike, callData: BytesLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'eduToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'executeProposal'): TypedContractMethod<
      [proposalId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getProposalState'): TypedContractMethod<
      [proposalId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'hasVoted'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'proposalCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'proposalThreshold'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'proposals'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, bigint, bigint, bigint, bigint, boolean, boolean, string, string] & {id: bigint, proposer: string, description: string, forVotes: bigint, againstVotes: bigint, startBlock: bigint, endBlock: bigint, executed: boolean, canceled: boolean, target: string, callData: string }],
      'view'
    >;
getFunction(nameOrSignature: 'quorumThreshold'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setProposalThreshold'): TypedContractMethod<
      [_threshold: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setQuorumThreshold'): TypedContractMethod<
      [_quorum: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setVotingPeriod'): TypedContractMethod<
      [_period: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'vote'): TypedContractMethod<
      [proposalId: BigNumberish, support: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'voteChoice'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'voteSnapshot'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'votingPeriod'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'ProposalCanceled'): TypedContractEvent<ProposalCanceledEvent.InputTuple, ProposalCanceledEvent.OutputTuple, ProposalCanceledEvent.OutputObject>;
getEvent(key: 'ProposalCreated'): TypedContractEvent<ProposalCreatedEvent.InputTuple, ProposalCreatedEvent.OutputTuple, ProposalCreatedEvent.OutputObject>;
getEvent(key: 'ProposalExecuted'): TypedContractEvent<ProposalExecutedEvent.InputTuple, ProposalExecutedEvent.OutputTuple, ProposalExecutedEvent.OutputObject>;
getEvent(key: 'ProposalThresholdUpdated'): TypedContractEvent<ProposalThresholdUpdatedEvent.InputTuple, ProposalThresholdUpdatedEvent.OutputTuple, ProposalThresholdUpdatedEvent.OutputObject>;
getEvent(key: 'QuorumUpdated'): TypedContractEvent<QuorumUpdatedEvent.InputTuple, QuorumUpdatedEvent.OutputTuple, QuorumUpdatedEvent.OutputObject>;
getEvent(key: 'Voted'): TypedContractEvent<VotedEvent.InputTuple, VotedEvent.OutputTuple, VotedEvent.OutputObject>;
getEvent(key: 'VotingPeriodUpdated'): TypedContractEvent<VotingPeriodUpdatedEvent.InputTuple, VotingPeriodUpdatedEvent.OutputTuple, VotingPeriodUpdatedEvent.OutputObject>;

    filters: {
      
      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'ProposalCanceled(uint256)': TypedContractEvent<ProposalCanceledEvent.InputTuple, ProposalCanceledEvent.OutputTuple, ProposalCanceledEvent.OutputObject>;
      ProposalCanceled: TypedContractEvent<ProposalCanceledEvent.InputTuple, ProposalCanceledEvent.OutputTuple, ProposalCanceledEvent.OutputObject>;
    

      'ProposalCreated(uint256,address,string,uint256,uint256)': TypedContractEvent<ProposalCreatedEvent.InputTuple, ProposalCreatedEvent.OutputTuple, ProposalCreatedEvent.OutputObject>;
      ProposalCreated: TypedContractEvent<ProposalCreatedEvent.InputTuple, ProposalCreatedEvent.OutputTuple, ProposalCreatedEvent.OutputObject>;
    

      'ProposalExecuted(uint256)': TypedContractEvent<ProposalExecutedEvent.InputTuple, ProposalExecutedEvent.OutputTuple, ProposalExecutedEvent.OutputObject>;
      ProposalExecuted: TypedContractEvent<ProposalExecutedEvent.InputTuple, ProposalExecutedEvent.OutputTuple, ProposalExecutedEvent.OutputObject>;
    

      'ProposalThresholdUpdated(uint256)': TypedContractEvent<ProposalThresholdUpdatedEvent.InputTuple, ProposalThresholdUpdatedEvent.OutputTuple, ProposalThresholdUpdatedEvent.OutputObject>;
      ProposalThresholdUpdated: TypedContractEvent<ProposalThresholdUpdatedEvent.InputTuple, ProposalThresholdUpdatedEvent.OutputTuple, ProposalThresholdUpdatedEvent.OutputObject>;
    

      'QuorumUpdated(uint256)': TypedContractEvent<QuorumUpdatedEvent.InputTuple, QuorumUpdatedEvent.OutputTuple, QuorumUpdatedEvent.OutputObject>;
      QuorumUpdated: TypedContractEvent<QuorumUpdatedEvent.InputTuple, QuorumUpdatedEvent.OutputTuple, QuorumUpdatedEvent.OutputObject>;
    

      'Voted(uint256,address,bool,uint256)': TypedContractEvent<VotedEvent.InputTuple, VotedEvent.OutputTuple, VotedEvent.OutputObject>;
      Voted: TypedContractEvent<VotedEvent.InputTuple, VotedEvent.OutputTuple, VotedEvent.OutputObject>;
    

      'VotingPeriodUpdated(uint256)': TypedContractEvent<VotingPeriodUpdatedEvent.InputTuple, VotingPeriodUpdatedEvent.OutputTuple, VotingPeriodUpdatedEvent.OutputObject>;
      VotingPeriodUpdated: TypedContractEvent<VotingPeriodUpdatedEvent.InputTuple, VotingPeriodUpdatedEvent.OutputTuple, VotingPeriodUpdatedEvent.OutputObject>;
    
    };
  }