/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'ERC20Mock', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ERC20Mock__factory>
getContractFactory(name: 'EduPlatform', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.EduPlatform__factory>
getContractFactory(name: 'GameLogic', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.GameLogic__factory>
getContractFactory(name: 'Governance', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Governance__factory>
getContractFactory(name: 'MembershipNFT', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MembershipNFT__factory>
getContractFactory(name: 'IGameItem', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IGameItem__factory>
getContractFactory(name: 'IGameLogic', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IGameLogic__factory>
getContractFactory(name: 'QuestManager', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.QuestManager__factory>
getContractFactory(name: 'SimplePaymaster', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SimplePaymaster__factory>
getContractFactory(name: 'IGameLogic', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IGameLogic__factory>
getContractFactory(name: 'Staking', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Staking__factory>
getContractFactory(name: 'EduToken', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.EduToken__factory>
getContractFactory(name: 'GameItem', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.GameItem__factory>

  getContractAt(name: 'ERC20Mock', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ERC20Mock>
getContractAt(name: 'EduPlatform', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.EduPlatform>
getContractAt(name: 'GameLogic', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.GameLogic>
getContractAt(name: 'Governance', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Governance>
getContractAt(name: 'MembershipNFT', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MembershipNFT>
getContractAt(name: 'IGameItem', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IGameItem>
getContractAt(name: 'IGameLogic', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IGameLogic>
getContractAt(name: 'QuestManager', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.QuestManager>
getContractAt(name: 'SimplePaymaster', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SimplePaymaster>
getContractAt(name: 'IGameLogic', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IGameLogic>
getContractAt(name: 'Staking', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Staking>
getContractAt(name: 'EduToken', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.EduToken>
getContractAt(name: 'GameItem', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.GameItem>

  deployContract(name: 'ERC20Mock', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ERC20Mock>
deployContract(name: 'EduPlatform', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.EduPlatform>
deployContract(name: 'GameLogic', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.GameLogic>
deployContract(name: 'Governance', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Governance>
deployContract(name: 'MembershipNFT', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MembershipNFT>
deployContract(name: 'IGameItem', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IGameItem>
deployContract(name: 'IGameLogic', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IGameLogic>
deployContract(name: 'QuestManager', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.QuestManager>
deployContract(name: 'SimplePaymaster', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SimplePaymaster>
deployContract(name: 'IGameLogic', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IGameLogic>
deployContract(name: 'Staking', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Staking>
deployContract(name: 'EduToken', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.EduToken>
deployContract(name: 'GameItem', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.GameItem>

  deployContract(name: 'ERC20Mock', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ERC20Mock>
deployContract(name: 'EduPlatform', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.EduPlatform>
deployContract(name: 'GameLogic', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.GameLogic>
deployContract(name: 'Governance', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Governance>
deployContract(name: 'MembershipNFT', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MembershipNFT>
deployContract(name: 'IGameItem', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IGameItem>
deployContract(name: 'IGameLogic', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IGameLogic>
deployContract(name: 'QuestManager', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.QuestManager>
deployContract(name: 'SimplePaymaster', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SimplePaymaster>
deployContract(name: 'IGameLogic', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IGameLogic>
deployContract(name: 'Staking', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Staking>
deployContract(name: 'EduToken', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.EduToken>
deployContract(name: 'GameItem', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.GameItem>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  