/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as questManagerSol from './QuestManager.sol/index.js';
export type { questManagerSol };
import type * as stakingSol from './Staking.sol/index.js';
export type { stakingSol };
export type { ERC20Mock } from './ERC20Mock.js';
export type { EduPlatform } from './EduPlatform.js';
export type { EduToken } from './EduToken.js';
export type { GameItem } from './GameItem.js';
export type { GameLogic } from './GameLogic.js';
export type { Governance } from './Governance.js';
export type { MembershipNFT } from './MembershipNFT.js';
export type { SimplePaymaster } from './SimplePaymaster.js';
export * as factories from './factories/index.js';
export { ERC20Mock__factory } from './factories/ERC20Mock__factory.js';
export { EduPlatform__factory } from './factories/EduPlatform__factory.js';
export { GameLogic__factory } from './factories/GameLogic__factory.js';
export { Governance__factory } from './factories/Governance__factory.js';
export { MembershipNFT__factory } from './factories/MembershipNFT__factory.js';
export type { IGameItem } from './QuestManager.sol/IGameItem.js';
export { IGameItem__factory } from './factories/QuestManager.sol/IGameItem__factory.js';
export type { IGameLogic } from './QuestManager.sol/IGameLogic.js';
export { IGameLogic__factory } from './factories/QuestManager.sol/IGameLogic__factory.js';
export type { QuestManager } from './QuestManager.sol/QuestManager.js';
export { QuestManager__factory } from './factories/QuestManager.sol/QuestManager__factory.js';
export { SimplePaymaster__factory } from './factories/SimplePaymaster__factory.js';
export type { Staking } from './Staking.sol/Staking.js';
export { Staking__factory } from './factories/Staking.sol/Staking__factory.js';
export { EduToken__factory } from './factories/EduToken__factory.js';
export { GameItem__factory } from './factories/GameItem__factory.js';