/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace SimplePaymaster {
      
    export type UserOperationStruct = {sender: AddressLike, nonce: BigNumberish, initCode: BytesLike, callData: BytesLike, callGasLimit: BigNumberish, verificationGasLimit: BigNumberish, preVerificationGas: BigNumberish, maxFeePerGas: BigNumberish, maxPriorityFeePerGas: BigNumberish, paymasterAndData: AddressLike, signature: BytesLike}

    export type UserOperationStructOutput = [sender: string, nonce: bigint, initCode: string, callData: string, callGasLimit: bigint, verificationGasLimit: bigint, preVerificationGas: bigint, maxFeePerGas: bigint, maxPriorityFeePerGas: bigint, paymasterAndData: string, signature: string] & {sender: string, nonce: bigint, initCode: string, callData: string, callGasLimit: bigint, verificationGasLimit: bigint, preVerificationGas: bigint, maxFeePerGas: bigint, maxPriorityFeePerGas: bigint, paymasterAndData: string, signature: string }
  
    }

  export interface SimplePaymasterInterface extends Interface {
    getFunction(nameOrSignature: "entryPoint" | "postOp" | "validatePaymasterUserOp" | "withdraw"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'entryPoint', values?: undefined): string;
encodeFunctionData(functionFragment: 'postOp', values: [BigNumberish, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'validatePaymasterUserOp', values: [SimplePaymaster.UserOperationStruct, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'withdraw', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'entryPoint', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'postOp', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'validatePaymasterUserOp', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
  }

  

  export interface SimplePaymaster extends BaseContract {
    
    connect(runner?: ContractRunner | null): SimplePaymaster;
    waitForDeployment(): Promise<this>;

    interface: SimplePaymasterInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    entryPoint: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    postOp: TypedContractMethod<
      [arg0: BigNumberish, arg1: BytesLike, arg2: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    validatePaymasterUserOp: TypedContractMethod<
      [userOp: SimplePaymaster.UserOperationStruct, arg1: BytesLike, arg2: BigNumberish, ],
      [[string, bigint] & {context: string, validationData: bigint }],
      'view'
    >
    

    
    withdraw: TypedContractMethod<
      [to: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'entryPoint'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'postOp'): TypedContractMethod<
      [arg0: BigNumberish, arg1: BytesLike, arg2: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'validatePaymasterUserOp'): TypedContractMethod<
      [userOp: SimplePaymaster.UserOperationStruct, arg1: BytesLike, arg2: BigNumberish, ],
      [[string, bigint] & {context: string, validationData: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [to: AddressLike, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }