/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IGameLogic, IGameLogicInterface } from "../../Staking.sol/IGameLogic.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "player",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "grantXP",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IGameLogic__factory {
    static readonly abi = _abi;
    static createInterface(): IGameLogicInterface {
      return new Interface(_abi) as IGameLogicInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IGameLogic {
      return new Contract(address, _abi, runner) as unknown as IGameLogic;
    }
  }
  