/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IGameLogic__factory } from './IGameLogic__factory.js';
export { Staking__factory } from './Staking__factory.js';