/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface StakingInterface extends Interface {
    getFunction(nameOrSignature: "claimRewards" | "earned" | "gameLogic" | "owner" | "renounceOwnership" | "rewardRate" | "setRewardRate" | "stake" | "stakes" | "stakingToken" | "transferOwnership" | "withdraw"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "OwnershipTransferred" | "RewardRateUpdated" | "RewardsClaimed" | "Staked" | "Withdrawn"): EventFragment;

    encodeFunctionData(functionFragment: 'claimRewards', values?: undefined): string;
encodeFunctionData(functionFragment: 'earned', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'gameLogic', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'rewardRate', values?: undefined): string;
encodeFunctionData(functionFragment: 'setRewardRate', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'stake', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'stakes', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'stakingToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'withdraw', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'claimRewards', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'earned', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'gameLogic', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rewardRate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setRewardRate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'stake', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'stakes', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'stakingToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
  }

  
    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RewardRateUpdatedEvent {
      export type InputTuple = [newRate: BigNumberish];
      export type OutputTuple = [newRate: bigint];
      export interface OutputObject {newRate: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RewardsClaimedEvent {
      export type InputTuple = [user: AddressLike, xp: BigNumberish];
      export type OutputTuple = [user: string, xp: bigint];
      export interface OutputObject {user: string, xp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace StakedEvent {
      export type InputTuple = [user: AddressLike, amount: BigNumberish];
      export type OutputTuple = [user: string, amount: bigint];
      export interface OutputObject {user: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawnEvent {
      export type InputTuple = [user: AddressLike, amount: BigNumberish];
      export type OutputTuple = [user: string, amount: bigint];
      export interface OutputObject {user: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Staking extends BaseContract {
    
    connect(runner?: ContractRunner | null): Staking;
    waitForDeployment(): Promise<this>;

    interface: StakingInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    claimRewards: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    earned: TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    gameLogic: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    rewardRate: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    setRewardRate: TypedContractMethod<
      [_rate: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    stake: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    stakes: TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, bigint, bigint] & {amount: bigint, rewardDebt: bigint, lastUpdate: bigint }],
      'view'
    >
    

    
    stakingToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    withdraw: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'claimRewards'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'earned'): TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'gameLogic'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'rewardRate'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'setRewardRate'): TypedContractMethod<
      [_rate: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'stake'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'stakes'): TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, bigint, bigint] & {amount: bigint, rewardDebt: bigint, lastUpdate: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'stakingToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'RewardRateUpdated'): TypedContractEvent<RewardRateUpdatedEvent.InputTuple, RewardRateUpdatedEvent.OutputTuple, RewardRateUpdatedEvent.OutputObject>;
getEvent(key: 'RewardsClaimed'): TypedContractEvent<RewardsClaimedEvent.InputTuple, RewardsClaimedEvent.OutputTuple, RewardsClaimedEvent.OutputObject>;
getEvent(key: 'Staked'): TypedContractEvent<StakedEvent.InputTuple, StakedEvent.OutputTuple, StakedEvent.OutputObject>;
getEvent(key: 'Withdrawn'): TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;

    filters: {
      
      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'RewardRateUpdated(uint256)': TypedContractEvent<RewardRateUpdatedEvent.InputTuple, RewardRateUpdatedEvent.OutputTuple, RewardRateUpdatedEvent.OutputObject>;
      RewardRateUpdated: TypedContractEvent<RewardRateUpdatedEvent.InputTuple, RewardRateUpdatedEvent.OutputTuple, RewardRateUpdatedEvent.OutputObject>;
    

      'RewardsClaimed(address,uint256)': TypedContractEvent<RewardsClaimedEvent.InputTuple, RewardsClaimedEvent.OutputTuple, RewardsClaimedEvent.OutputObject>;
      RewardsClaimed: TypedContractEvent<RewardsClaimedEvent.InputTuple, RewardsClaimedEvent.OutputTuple, RewardsClaimedEvent.OutputObject>;
    

      'Staked(address,uint256)': TypedContractEvent<StakedEvent.InputTuple, StakedEvent.OutputTuple, StakedEvent.OutputObject>;
      Staked: TypedContractEvent<StakedEvent.InputTuple, StakedEvent.OutputTuple, StakedEvent.OutputObject>;
    

      'Withdrawn(address,uint256)': TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;
      Withdrawn: TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;
    
    };
  }