/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IGameItem, IGameItemInterface } from "../../QuestManager.sol/IGameItem.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "to",
        "type": "address"
      },
      {
        "internalType": "string",
        "name": "uri",
        "type": "string"
      }
    ],
    "name": "mint",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IGameItem__factory {
    static readonly abi = _abi;
    static createInterface(): IGameItemInterface {
      return new Interface(_abi) as IGameItemInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IGameItem {
      return new Contract(address, _abi, runner) as unknown as IGameItem;
    }
  }
  